### ISSUE TITLE
Exception thrown when user reaches milestone

### ISSUE THREAD

**Issue by Romejanic** [Romejanic/time-wasted-meter#1]
Looks like a basic error caused by an out of bounds number when calculating the progress percentage.

```
01.08 04:08:58 [Server] WARN [TimeWastedMeter] Task #10 for TimeWastedMeter v1.1.0 generated an exception
01.08 04:08:58 [Server] INFO java.lang.IllegalArgumentException: Progress must be between 0.0 and 1.0 (1.000028)
01.08 04:08:58 [Server] INFO at com.google.common.base.Preconditions.checkArgument(Preconditions.java:220) ~[guava-31.0.1-jre.jar:?]
01.08 04:08:58 [Server] INFO at org.bukkit.craftbukkit.v1_19_R1.boss.CraftBossBar.setProgress(CraftBossBar.java:158) ~[paper-1.19.jar:git-Paper-81]
01.08 04:08:58 [Server] INFO at macs.timewasted.meter.TimeMeter.refreshBar(TimeMeter.java:90) ~[TimeWastedMeter.jar:?]
01.08 04:08:58 [Server] INFO at macs.timewasted.meter.TimeMeter.run(TimeMeter.java:80) ~[TimeWastedMeter.jar:?]
01.08 04:08:58 [Server] INFO at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.jar:git-Paper-81]
01.08 04:08:58 [Server] INFO at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.jar:git-Paper-81]
01.08 04:08:58 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1491) ~[paper-1.19.jar:git-Paper-81]
01.08 04:08:58 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.jar:git-Paper-81]
01.08 04:08:58 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1415) ~[paper-1.19.jar:git-Paper-81]
01.08 04:08:58 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[paper-1.19.jar:git-Paper-81]
01.08 04:08:58 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:303) ~[paper-1.19.jar:git-Paper-81]
01.08 04:08:58 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

Sometimes causes the bar to get stuck at the end for a few ticks so it should be fixed to improve user experience.

**Comment by Romejanic** [comment]
Fixed in next release
